# Generated by Django 2.0 on 2022-01-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220123_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charges',
            name='redeem_wallet_amount',
        ),
        migrations.AddField(
            model_name='charges',
            name='redeem_wallet_percentage',
            field=models.FloatField(blank=True, default=0, help_text='in percentage (%)', null=True),
        ),
    ]
