# Generated by Django 3.2 on 2022-04-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220415_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicaltype',
            name='group',
        ),
        migrations.AddField(
            model_name='vehicaltype',
            name='group',
            field=models.ManyToManyField(to='main.VehicalGroup'),
        ),
    ]
