# Generated by Django 2.0 on 2021-12-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_be_paid', models.IntegerField(blank=True, default=0, null=True)),
                ('vendor_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('is_complete_vendor', models.BooleanField(default=False)),
                ('is_complete_customer', models.BooleanField(default=False)),
                ('vendor_balance', models.IntegerField(blank=True, default=None, null=True)),
                ('customer_balance', models.IntegerField(blank=True, default=None, null=True)),
                ('partial_payment', models.IntegerField(blank=True, default=None, null=True)),
                ('final_payment', models.IntegerField(blank=True, default=None, null=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_detail', to='main.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('debit', models.BooleanField(default=False)),
                ('credit', models.BooleanField(default=False)),
                ('running_balance', models.IntegerField(default=0)),
                ('running_balance_redeem', models.IntegerField(default=0)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('is_cashback', models.BooleanField(default=False)),
                ('is_online', models.BooleanField()),
                ('razorpay_payment_id', models.CharField(max_length=256, null=True)),
                ('razorpay_order_id', models.CharField(max_length=256, null=True)),
                ('razorpay_signature', models.CharField(max_length=256, null=True)),
                ('vendor_to_customer', models.BooleanField(default=False)),
                ('vendor_to_company', models.BooleanField(default=False)),
                ('customer_to_vendor', models.BooleanField(default=False)),
                ('customer_to_company', models.BooleanField(default=False)),
                ('company_to_customer', models.BooleanField(default=False)),
                ('company_to_vendor', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(blank=True, max_length=400, null=True)),
                ('paymentdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.PaymentDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('redeem_balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('deactivate_amount', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to='main.CustomerProfile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to='main.OwnerProfile')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.Wallet'),
        ),
    ]
